# Generated by Django 5.2 on 2025-05-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_ticket_ticket_type_event_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('FEENS', 'FEENS'), ('edu', 'EDU'), ('law', 'Law'), ('BS', 'BS')], default='FEENS', max_length=100),
        ),
    ]
