# Generated by Django 5.2 on 2025-05-11 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_is_email_verified_alter_club_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 11, 9, 54, 52, 881860, tzinfo=datetime.timezone.utc)),
        ),
    ]
